[build]
  base = "exampleSite/"
  publish = "exampleSite/public"
  command = "hugo --gc --themesDir ../.. --config config-prod.toml"

[build.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_THEME = "repo"