locale = "en-us"
title = "Massively"
baseURL = "https://hugo-theme-massively.netlify.com/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "term", "section"]



# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  label = "English"
[languages.es]
  label = "Español"
  title = "Massively - Versión Español"
#[languages.fr]
#  label = "Français"
#  title = "Massively - Version Française"
